version: '3'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: clean-node-api
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - 27017:27017
    networks:
      - dev-default

  db-client:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: jeffersonrt
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2020!
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2020!
    links:
      - db
    depends_on:
      - db
    networks:
      - dev-default

networks:
  dev-default:
    driver: bridge
